"""after delpoy Migration

Revision ID: 89b3ccb3d387
Revises: 6ff26a14e4f2
Create Date: 2017-11-01 23:23:47.475243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b3ccb3d387'
down_revision = '6ff26a14e4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'date_posted')
    # ### end Alembic commands ###
