"""fifth migration

Revision ID: 927e81980f4d
Revises: 77c1c6624d4f
Create Date: 2017-11-01 10:15:25.978614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927e81980f4d'
down_revision = '77c1c6624d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
